# .github/ISSUE_TEMPLATE/config.yml
blank_issues_enabled: false
contact_links:
  - name: Questions or Feedback
    url: https://github.com/DarsenOP/tapece/discussions
    about: Use Discussions for general help.
